mysql:
  image: mysql:8
  rootPassword: root
  database: clientes
  servicePort: 3306
backend:
  image: pixelian/clientes-back:latest
  port: 3000
frontend:
  image: pixelian/clientes-front:v2
  port: 80